/**
 * QuestionCanvas - Main canvas area for displaying generated questions
 * Renders a real-time stream of questions as they are generated by the AI agent.
 * Features: Streaming markdown display with ChatGPT-like typing effect
 */
import React, { useRef, useEffect } from 'react'
import { motion, AnimatePresence } from 'motion/react'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { AgentStatusBar } from './AgentStatusBar'
import { QuestionCard } from './QuestionCard'
import { Sparkles, FileQuestion, Download, CheckCircle, Loader2 } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkMath from 'remark-math'
import rehypeKatex from 'rehype-katex'
import 'katex/dist/katex.min.css'
import { cn } from '@/lib/utils'

interface GeneratedQuestion {
  question_id: string
  type: string
  difficulty: string
  blooms_level?: string
  question_text: string
  options?: string[]
  correct_answer: string
  explanation?: string
  status?: 'pending' | 'approved' | 'rejected'
}

interface QuestionCanvasProps {
  // Generation state
  isGenerating: boolean
  currentAction: string | null
  thinkingSteps: string[]
  progress: { current: number; total: number }
  foundSources: Array<{ id: string; title: string; excerpt: string }>

  // Questions
  questions: GeneratedQuestion[]
  streamingContent?: string

  // Actions
  onApprove?: (id: string) => void
  onReject?: (id: string) => void
  onEdit?: (id: string, data: Partial<GeneratedQuestion>) => void
  onRegenerate?: (id: string) => void
  onDelete?: (id: string) => void
  onApproveAll?: () => void
  onExport?: () => void
}

/**
 * StreamingMarkdown - Renders markdown content as it streams in
 * Hides the JSON block at the end for cleaner display during streaming
 */
function StreamingMarkdown({ content }: { content: string }) {
  // Filter out the JSON code block at the end (it's for parsing, not display)
  // The prompt outputs readable markdown first, then JSON at the end
  const displayContent = React.useMemo(() => {
    let processed = content

    // Remove completed JSON code blocks (```json ... ```)
    processed = processed.replace(/```json[\s\S]*?```/g, '')

    // Also remove partial/in-progress JSON blocks (```json ... without closing ```)
    // This handles the case where the model is in the middle of outputting JSON
    const partialJsonMatch = processed.match(/```json[\s\S]*$/)
    if (partialJsonMatch) {
      processed = processed.substring(0, processed.indexOf('```json'))
    }

    // Remove any trailing partial code fence that might be starting
    processed = processed.replace(/```\s*$/, '')

    return processed.trim()
  }, [content])

  if (!displayContent) {
    return null
  }

  return (
    <ReactMarkdown
      remarkPlugins={[remarkMath]}
      rehypePlugins={[rehypeKatex]}
      className={cn(
        'prose prose-sm dark:prose-invert max-w-none',
        // Custom styling for streaming markdown
        '[&>h2]:text-lg [&>h2]:font-semibold [&>h2]:text-primary [&>h2]:mt-4 [&>h2]:mb-2',
        '[&>h3]:text-base [&>h3]:font-medium [&>h3]:text-foreground [&>h3]:mt-3 [&>h3]:mb-1',
        '[&>p]:text-sm [&>p]:text-foreground/90 [&>p]:my-2',
        '[&>ul]:text-sm [&>ul]:my-2 [&>ul]:space-y-1',
        '[&>ul>li]:text-foreground/90',
        '[&>hr]:my-3 [&>hr]:border-border',
        '[&_strong]:text-foreground [&_strong]:font-semibold',
        '[&_code]:text-xs [&_code]:bg-muted [&_code]:px-1 [&_code]:py-0.5 [&_code]:rounded'
      )}
    >
      {displayContent}
    </ReactMarkdown>
  )
}

export function QuestionCanvas({
  isGenerating,
  currentAction,
  thinkingSteps,
  progress,
  foundSources,
  questions,
  streamingContent,
  onApprove,
  onReject,
  onEdit,
  onRegenerate,
  onDelete,
  onApproveAll,
  onExport,
}: QuestionCanvasProps) {
  const pendingCount = questions.filter(q => q.status === 'pending' || !q.status).length
  const approvedCount = questions.filter(q => q.status === 'approved').length
  const scrollRef = useRef<HTMLDivElement>(null)

  // Auto-scroll to bottom when new questions arrive or streaming
  useEffect(() => {
    if (scrollRef.current && (isGenerating || questions.length > 0)) {
      scrollRef.current.scrollTo({
        top: scrollRef.current.scrollHeight,
        behavior: 'smooth'
      })
    }
  }, [questions.length, streamingContent, isGenerating])

  return (
    <div className="flex flex-col h-full">
      {/* Status Bar */}
      <div className="p-4 border-b">
        <AgentStatusBar
          isGenerating={isGenerating}
          currentAction={currentAction}
          thinkingSteps={thinkingSteps}
          progress={progress}
          foundSources={foundSources}
        />
      </div>

      {/* Canvas Content */}
      <ScrollArea className="flex-1" ref={scrollRef}>
        <div className="p-4 space-y-4">
          <AnimatePresence mode="popLayout">
            {questions.length === 0 && !isGenerating ? (
              <EmptyCanvasState />
            ) : (
              <>
                {questions.map((question, index) => (
                  <motion.div
                    key={question.question_id}
                    initial={{ opacity: 0, y: 20, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    transition={{ duration: 0.3, ease: 'easeOut' }}
                  >
                    <QuestionCard
                      question={question}
                      index={index}
                      isStreaming={false}
                      onApprove={onApprove}
                      onReject={onReject}
                      onEdit={onEdit}
                      onRegenerate={onRegenerate}
                      onDelete={onDelete}
                    />
                  </motion.div>
                ))}

                {/* Streaming content preview - shows while generating next question */}
                {isGenerating && (
                  <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    transition={{ duration: 0.2 }}
                  >
                    <Card className="p-4 bg-card border border-border overflow-hidden">
                      {/* Header with spinner */}
                      <div className="flex items-center gap-3 mb-4">
                        <div className="flex items-center justify-center h-8 w-8 rounded-full bg-primary/10">
                          <Loader2 className="h-4 w-4 text-primary animate-spin" />
                        </div>
                        <div>
                          <p className="text-sm font-medium">
                            Generating Question {progress.current + 1} of {progress.total}
                          </p>
                          <p className="text-xs text-muted-foreground">
                            {streamingContent ? 'Streaming response...' : 'AI is crafting your question...'}
                          </p>
                        </div>
                      </div>

                      {/* Streaming markdown content OR skeleton */}
                      {streamingContent ? (
                        <div className="relative">
                          <StreamingMarkdown content={streamingContent} />
                          {/* Blinking cursor effect */}
                          <span className="inline-block w-2 h-4 bg-primary/80 ml-0.5 animate-pulse" />
                        </div>
                      ) : (
                        <div className="space-y-4">
                          {/* Question text skeleton */}
                          <div className="space-y-2">
                            <div className="h-4 bg-muted rounded animate-pulse w-full" />
                            <div className="h-4 bg-muted rounded animate-pulse w-5/6" />
                            <div className="h-4 bg-muted rounded animate-pulse w-4/6" />
                          </div>

                          {/* Options skeleton */}
                          <div className="space-y-2 pt-2">
                            <div className="flex items-center gap-3">
                              <div className="h-5 w-5 rounded-full bg-muted animate-pulse flex-shrink-0" />
                              <div className="h-4 bg-muted rounded animate-pulse flex-1" />
                            </div>
                            <div className="flex items-center gap-3">
                              <div className="h-5 w-5 rounded-full bg-muted animate-pulse flex-shrink-0" />
                              <div className="h-4 bg-muted rounded animate-pulse flex-1" />
                            </div>
                            <div className="flex items-center gap-3">
                              <div className="h-5 w-5 rounded-full bg-muted animate-pulse flex-shrink-0" />
                              <div className="h-4 bg-muted rounded animate-pulse flex-1" />
                            </div>
                            <div className="flex items-center gap-3">
                              <div className="h-5 w-5 rounded-full bg-muted animate-pulse flex-shrink-0" />
                              <div className="h-4 bg-muted rounded animate-pulse flex-1" />
                            </div>
                          </div>
                        </div>
                      )}
                    </Card>
                  </motion.div>
                )}
              </>
            )}
          </AnimatePresence>
        </div>
      </ScrollArea>

      {/* Footer Actions */}
      {questions.length > 0 && !isGenerating && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-4 border-t bg-muted/30"
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4 text-sm text-muted-foreground">
              <span>{questions.length} questions</span>
              <span className="text-yellow-600">{pendingCount} pending</span>
              <span className="text-green-600">{approvedCount} approved</span>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={onExport}>
                <Download className="h-4 w-4 mr-2" />
                Export
              </Button>
              {pendingCount > 0 && (
                <Button size="sm" onClick={onApproveAll}>
                  <CheckCircle className="h-4 w-4 mr-2" />
                  Approve All ({pendingCount})
                </Button>
              )}
            </div>
          </div>
        </motion.div>
      )}
    </div>
  )
}

function EmptyCanvasState() {
  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="flex flex-col items-center justify-center py-20 text-center"
    >
      <div className="rounded-full bg-primary/10 p-6 mb-4">
        <FileQuestion className="h-12 w-12 text-primary" />
      </div>
      <h3 className="text-lg font-semibold mb-2">No Questions Yet</h3>
      <p className="text-sm text-muted-foreground max-w-sm">
        Configure your generation settings and click "Generate" to create AI-powered questions.
        Questions will appear here in real-time.
      </p>
    </motion.div>
  )
}

export default QuestionCanvas

